name: Run Python tests

on: [push]

jobs:
  get-all-files:
    runs-on: ubuntu-latest
    steps:
      - uses: sigyl-actions/files-ls@v0.0.1
        id: step1
      - name: Dump Steps context
        env:
          GITHUB_CONTEXT: ${{ toJson(steps) }}
        run: echo "$GITHUB_CONTEXT"
    outputs:
      files: ${{steps.step1.outputs.files}}
  one:
    needs: [get-all-files]
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
      - name: Dump needs context
        env:
          NEEDS_CONTEXT: ${{ toJson(needs) }}
        run: echo "$NEEDS_CONTEXT"

  build:
    name: Run tests
    needs: [get-all-files]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8"]
        file: ${{ needs.get-all-files.outputs.files }}

    steps:
      - uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "Europe/London"
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install pytest pytest-md pytest-emoji
      - uses: pavelzw/pytest-action@v2
        with:
          emoji: true
          verbose: false
          job-summary: true
          