name: Run Python tests

on: [push]

jobs:
  get-all-files:
    runs-on: ubuntu-latest
    steps:
      - uses: sigyl-actions/files-ls@v0.0.1
    outputs:
      files: ${{steps.step1.outputs.files}}
    
  build:
    name: Run tests
    needs: [get-all-files]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8"]
        file: ${{jobs.get-all-files.outputs.files}}

    steps:
      - uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "Europe/London"
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install pytest pytest-md pytest-emoji
      - uses: pavelzw/pytest-action@v2
        with:
          emoji: true
          verbose: false
          job-summary: true
          